# Server port setting
#server:
#  port: 8080

spring:
  profiles:
    active: local # 기본 프로파일 설정

  # Jackson 시간대 설정 
  jackson:
    time-zone: Asia/Seoul

  # JPA Setting(JPA 공통 설정)
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # 메일 서버 기본 설정
  mail:
    host: smtp.gmail.com  #이메일 전송에 사용할 메일 서버의 호스트 이름으로 Gmail을 활용한다.
    port: 587             #Gmail 포트로 default값
    properties: # 말그대로 세팅정보로 후에 Config 설정에서 사용된다.
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          # 타임아웃 설정
          connectiontimeout: 5000         # SMTP 서버에 연결하는 데 허용되는 최대 시간(밀리초) : 5초
          timeout: 5000                   # SMTP 서버에서 응답을 기다리는 최대 시간(밀리초) : 5초
          writetimeout: 5000              # SMTP 서버에 데이터를 전송할 때 허용되는 최대 시간(밀리초) : 5초
      auth-code-expiration-millis: 1800000  # 인증코드가 만료되기까지 시간 30 * 60 * 1000 == 30분

# 기본 로깅 설정
logging:
  level:
    root: INFO
    com.portfolio.aperio: DEBUG


